<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('hotels')->truncate();

        $hotels = [
            // ==================== HÀ NỘI ====================
            [
                'name'                  => 'The Grand Hanoi Hotel',
                'city'                  => 'Ha Noi',
                'address'               => '49 Ba Trieu Street, Hoan Kiem, Ha Noi',
                'image'                 => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
                'price_per_night'       => 120.00,
                'total_rooms'           => 80,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Luxury hotel in the heart of Hanoi Old Quarter with stunning views of Hoan Kiem Lake.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 1250,
                'distance_from_centre'  => 0.5,
                'latitude'              => 21.0285,
                'longitude'             => 105.8542,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Pool', 'Gym', 'Restaurant', 'Bar', 'Free Parking', 'Spa access']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Hanoi Old Quarter Boutique',
                'city'                  => 'Ha Noi',
                'address'               => '12 Hang Bac, Hoan Kiem, Ha Noi',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 75.00,
                'total_rooms'           => 30,
                'max_guests_per_room'   => 2,
                'rating'                => 4.6,
                'description'           => 'Charming boutique hotel in the heart of Hanoi Old Quarter.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 890,
                'distance_from_centre'  => 0.3,
                'latitude'              => 21.0340,
                'longitude'             => 105.8520,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'TV', 'Towels']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Hanoi Lakeside View Hotel',
                'city'                  => 'Ha Noi',
                'address'               => '1 Dinh Tien Hoang, Hoan Kiem, Ha Noi',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 95.00,
                'total_rooms'           => 60,
                'max_guests_per_room'   => 2,
                'rating'                => 4.5,
                'description'           => 'Modern hotel overlooking the iconic Hoan Kiem Lake.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 760,
                'distance_from_centre'  => 0.1,
                'latitude'              => 21.0295,
                'longitude'             => 105.8520,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'Gym']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Hanoi Hostel & Backpacker',
                'city'                  => 'Ha Noi',
                'address'               => '5 Ngo Huyen, Hoan Kiem, Ha Noi',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 18.00,
                'total_rooms'           => 20,
                'max_guests_per_room'   => 6,
                'rating'                => 4.2,
                'description'           => 'Budget-friendly hostel perfect for backpackers exploring Hanoi.',
                'type'                  => 'Hostel',
                'star_rating'           => 2,
                'review_count'          => 430,
                'distance_from_centre'  => 0.4,
                'latitude'              => 21.0310,
                'longitude'             => 105.8490,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Towels', 'Hangers']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Sofitel Legend Metropole Hanoi',
                'city'                  => 'Ha Noi',
                'address'               => '15 Ngo Quyen Street, Hoan Kiem, Ha Noi',
                'image'                 => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
                'price_per_night'       => 280.00,
                'total_rooms'           => 244,
                'max_guests_per_room'   => 3,
                'rating'                => 4.9,
                'description'           => 'Iconic 5-star heritage hotel in the heart of Hanoi since 1901.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 3200,
                'distance_from_centre'  => 0.2,
                'latitude'              => 21.0260,
                'longitude'             => 105.8580,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Air Conditioning', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== HỒ CHÍ MINH ====================
            [
                'name'                  => 'Saigon Riverside Hotel',
                'city'                  => 'Ho Chi Minh',
                'address'               => '18 Ton Duc Thang, District 1, Ho Chi Minh',
                'image'                 => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
                'price_per_night'       => 95.00,
                'total_rooms'           => 120,
                'max_guests_per_room'   => 2,
                'rating'                => 4.5,
                'description'           => 'Modern hotel with panoramic views of the Saigon River.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 980,
                'distance_from_centre'  => 1.2,
                'latitude'              => 10.7769,
                'longitude'             => 106.7009,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'TV', 'Balcony']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Park Hyatt Saigon',
                'city'                  => 'Ho Chi Minh',
                'address'               => '2 Lam Son Square, District 1, Ho Chi Minh',
                'image'                 => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80',
                'price_per_night'       => 320.00,
                'total_rooms'           => 252,
                'max_guests_per_room'   => 3,
                'rating'                => 4.9,
                'description'           => 'Luxury 5-star hotel at the heart of Ho Chi Minh City.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 2800,
                'distance_from_centre'  => 0.3,
                'latitude'              => 10.7797,
                'longitude'             => 106.7040,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Air Conditioning']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Saigon Budget Inn',
                'city'                  => 'Ho Chi Minh',
                'address'               => '34 Bui Vien, District 1, Ho Chi Minh',
                'image'                 => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
                'price_per_night'       => 22.00,
                'total_rooms'           => 40,
                'max_guests_per_room'   => 4,
                'rating'                => 4.1,
                'description'           => 'Affordable guesthouse on the famous backpacker street.',
                'type'                  => 'Guest House',
                'star_rating'           => 2,
                'review_count'          => 620,
                'distance_from_centre'  => 0.8,
                'latitude'              => 10.7680,
                'longitude'             => 106.6920,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'TV', 'Towels']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Liberty Central Saigon Citypoint',
                'city'                  => 'Ho Chi Minh',
                'address'               => '59 Pasteur Street, District 1, Ho Chi Minh',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 110.00,
                'total_rooms'           => 170,
                'max_guests_per_room'   => 3,
                'rating'                => 4.4,
                'description'           => 'Contemporary hotel with rooftop pool in District 1.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 1450,
                'distance_from_centre'  => 0.5,
                'latitude'              => 10.7780,
                'longitude'             => 106.7010,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Gym', 'Restaurant', 'Bar']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'The Reverie Saigon',
                'city'                  => 'Ho Chi Minh',
                'address'               => '22-36 Nguyen Hue, District 1, Ho Chi Minh',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 380.00,
                'total_rooms'           => 286,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Ultra-luxury hotel on the iconic Nguyen Hue walking street.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 1900,
                'distance_from_centre'  => 0.1,
                'latitude'              => 10.7745,
                'longitude'             => 106.7030,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Hot Tub', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== ĐÀ NẴNG ====================
            [
                'name'                  => 'Da Nang Beach Resort',
                'city'                  => 'Da Nang',
                'address'               => '30 Vo Nguyen Giap, My An, Da Nang',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 150.00,
                'total_rooms'           => 60,
                'max_guests_per_room'   => 4,
                'rating'                => 4.8,
                'description'           => 'Beachfront resort on My Khe Beach with private pool.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 2100,
                'distance_from_centre'  => 3.5,
                'latitude'              => 16.0544,
                'longitude'             => 108.2022,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Gym', 'Spa access', 'Restaurant', 'Private Beach Area', 'Free Parking', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Hyatt Regency Da Nang',
                'city'                  => 'Da Nang',
                'address'               => '5 Truong Sa Street, Ngu Hanh Son, Da Nang',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 220.00,
                'total_rooms'           => 200,
                'max_guests_per_room'   => 4,
                'rating'                => 4.8,
                'description'           => 'World-class resort with multiple pools and beachfront access.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 3100,
                'distance_from_centre'  => 5.0,
                'latitude'              => 16.0200,
                'longitude'             => 108.2480,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Da Nang City Center Hotel',
                'city'                  => 'Da Nang',
                'address'               => '20 Bach Dang, Hai Chau, Da Nang',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 65.00,
                'total_rooms'           => 50,
                'max_guests_per_room'   => 2,
                'rating'                => 4.3,
                'description'           => 'Comfortable hotel near the Han River bridge.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 520,
                'distance_from_centre'  => 1.0,
                'latitude'              => 16.0678,
                'longitude'             => 108.2208,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'TV', 'Breakfast Included', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'InterContinental Da Nang Sun Peninsula',
                'city'                  => 'Da Nang',
                'address'               => 'Bai But, Son Tra Peninsula, Da Nang',
                'image'                 => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600&q=80',
                'price_per_night'       => 450.00,
                'total_rooms'           => 197,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Award-winning luxury resort nestled on Son Tra Peninsula.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 2400,
                'distance_from_centre'  => 8.0,
                'latitude'              => 16.1200,
                'longitude'             => 108.2800,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Waterfront']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== HỘI AN ====================
            [
                'name'                  => 'Hoi An Ancient Town Boutique',
                'city'                  => 'Hoi An',
                'address'               => '5 Le Loi Street, Hoi An Ancient Town',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 85.00,
                'total_rooms'           => 30,
                'max_guests_per_room'   => 2,
                'rating'                => 4.9,
                'description'           => 'Charming boutique hotel inside UNESCO-listed Hoi An Ancient Town.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 760,
                'distance_from_centre'  => 0.3,
                'latitude'              => 15.8800,
                'longitude'             => 108.3380,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Balcony', 'TV', 'Towels']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Four Seasons Resort The Nam Hai',
                'city'                  => 'Hoi An',
                'address'               => 'Block Ha My Dong B, Dien Duong, Hoi An',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 580.00,
                'total_rooms'           => 100,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Ultra-luxury beach resort with private villas and 3 pools.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 1800,
                'distance_from_centre'  => 4.0,
                'latitude'              => 15.9200,
                'longitude'             => 108.3600,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Hot Tub', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Hoi An Eco Lodge',
                'city'                  => 'Hoi An',
                'address'               => '132 Cua Dai Road, Hoi An',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 45.00,
                'total_rooms'           => 20,
                'max_guests_per_room'   => 2,
                'rating'                => 4.5,
                'description'           => 'Peaceful eco-friendly lodge surrounded by rice paddies.',
                'type'                  => 'Guest House',
                'star_rating'           => 3,
                'review_count'          => 340,
                'distance_from_centre'  => 2.5,
                'latitude'              => 15.8650,
                'longitude'             => 108.3700,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Free Parking', 'Bicycle rental']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],

            // ==================== PHÚ QUỐC ====================
            [
                'name'                  => 'Phu Quoc Paradise Villa',
                'city'                  => 'Phu Quoc',
                'address'               => 'Long Beach Road, Duong To, Phu Quoc',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 200.00,
                'total_rooms'           => 40,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Overwater villas with private plunge pools overlooking the Gulf of Thailand.',
                'type'                  => 'Villa',
                'star_rating'           => 5,
                'review_count'          => 430,
                'distance_from_centre'  => 5.0,
                'latitude'              => 10.2899,
                'longitude'             => 103.9840,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Hot Tub', 'Kitchen', 'Waterfront', 'Private Beach Area', 'BBQ Grill', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'JW Marriott Phu Quoc Emerald Bay',
                'city'                  => 'Phu Quoc',
                'address'               => 'Khem Beach, An Thoi, Phu Quoc',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 520.00,
                'total_rooms'           => 244,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Legendary resort inspired by a fictional French university on pristine Khem Beach.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 2600,
                'distance_from_centre'  => 9.0,
                'latitude'              => 10.1800,
                'longitude'             => 103.9700,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Waterfront', 'Hot Tub']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Phu Quoc Budget Hostel',
                'city'                  => 'Phu Quoc',
                'address'               => '118 Tran Hung Dao, Duong Dong, Phu Quoc',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 20.00,
                'total_rooms'           => 15,
                'max_guests_per_room'   => 8,
                'rating'                => 4.0,
                'description'           => 'Budget hostel close to Duong Dong night market.',
                'type'                  => 'Hostel',
                'star_rating'           => 1,
                'review_count'          => 280,
                'distance_from_centre'  => 1.0,
                'latitude'              => 10.2160,
                'longitude'             => 103.9580,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Towels']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],

            // ==================== NHA TRANG ====================
            [
                'name'                  => 'Nha Trang Ocean View Hotel',
                'city'                  => 'Nha Trang',
                'address'               => '78 Tran Phu Boulevard, Nha Trang',
                'image'                 => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600&q=80',
                'price_per_night'       => 75.00,
                'total_rooms'           => 100,
                'max_guests_per_room'   => 3,
                'rating'                => 4.3,
                'description'           => 'Seafront hotel on the famous Nha Trang beach promenade with rooftop bar.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 1540,
                'distance_from_centre'  => 1.8,
                'latitude'              => 12.2388,
                'longitude'             => 109.1967,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Bar', 'Restaurant', 'TV', 'Smoke Alarm']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Sheraton Nha Trang Hotel & Spa',
                'city'                  => 'Nha Trang',
                'address'               => '26-28 Tran Phu Street, Nha Trang',
                'image'                 => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
                'price_per_night'       => 180.00,
                'total_rooms'           => 278,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Luxury beachfront hotel with infinity pool overlooking the South China Sea.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 2200,
                'distance_from_centre'  => 0.5,
                'latitude'              => 12.2450,
                'longitude'             => 109.1940,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Air Conditioning', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash', 'PayPal']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Nha Trang Backpacker House',
                'city'                  => 'Nha Trang',
                'address'               => '15 Biet Thu Street, Nha Trang',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 15.00,
                'total_rooms'           => 25,
                'max_guests_per_room'   => 6,
                'rating'                => 4.1,
                'description'           => 'Lively hostel steps from the beach, popular with surfers.',
                'type'                  => 'Hostel',
                'star_rating'           => 2,
                'review_count'          => 390,
                'distance_from_centre'  => 1.5,
                'latitude'              => 12.2360,
                'longitude'             => 109.1920,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Towels', 'Smoke Alarm']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],

            // ==================== SAPA ====================
            [
                'name'                  => 'Sapa Mountain Lodge',
                'city'                  => 'Sapa',
                'address'               => '12 Muong Hoa Road, Sapa Town, Lao Cai',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 60.00,
                'total_rooms'           => 25,
                'max_guests_per_room'   => 2,
                'rating'                => 4.6,
                'description'           => 'Cozy mountain lodge with valley views, fireplace, and daily trekking tours.',
                'type'                  => 'Guest House',
                'star_rating'           => 3,
                'review_count'          => 320,
                'distance_from_centre'  => 2.1,
                'latitude'              => 22.3364,
                'longitude'             => 103.8438,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Radiant Heating', 'Iron', 'Towels']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Victoria Sapa Resort & Spa',
                'city'                  => 'Sapa',
                'address'               => 'Victoria Club, Sapa Town, Lao Cai',
                'image'                 => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
                'price_per_night'       => 140.00,
                'total_rooms'           => 77,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Colonial-style mountain resort with stunning Fansipan views.',
                'type'                  => 'Resort',
                'star_rating'           => 4,
                'review_count'          => 980,
                'distance_from_centre'  => 0.5,
                'latitude'              => 22.3380,
                'longitude'             => 103.8420,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Radiant Heating', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Sapa Homestay & Trekking',
                'city'                  => 'Sapa',
                'address'               => 'Cat Cat Village, Sapa, Lao Cai',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 25.00,
                'total_rooms'           => 10,
                'max_guests_per_room'   => 3,
                'rating'                => 4.8,
                'description'           => 'Authentic homestay with local H\'Mong family, trekking included.',
                'type'                  => 'Guest House',
                'star_rating'           => 2,
                'review_count'          => 210,
                'distance_from_centre'  => 3.0,
                'latitude'              => 22.3200,
                'longitude'             => 103.8300,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Breakfast Included', 'Radiant Heating', 'Towels']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],

            // ==================== HUẾ ====================
            [
                'name'                  => 'Hue Imperial Palace Hotel',
                'city'                  => 'Hue',
                'address'               => '23 Le Loi Street, Hue City',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 70.00,
                'total_rooms'           => 50,
                'max_guests_per_room'   => 2,
                'rating'                => 4.4,
                'description'           => 'Heritage hotel near the Imperial Citadel with traditional Vietnamese architecture.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 610,
                'distance_from_centre'  => 1.0,
                'latitude'              => 16.4637,
                'longitude'             => 107.5909,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'TV', 'Hair dryer', 'Safe', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'La Residence Hotel & Spa Hue',
                'city'                  => 'Hue',
                'address'               => '5 Le Loi Street, Hue City',
                'image'                 => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80',
                'price_per_night'       => 160.00,
                'total_rooms'           => 122,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Art deco boutique hotel on the Perfume River banks.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 1100,
                'distance_from_centre'  => 0.8,
                'latitude'              => 16.4620,
                'longitude'             => 107.5950,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Air Conditioning', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== HẠ LONG ====================
            [
                'name'                  => 'Ha Long Bay Cruise Hotel',
                'city'                  => 'Ha Long',
                'address'               => 'Hon Gai Harbour, Ha Long City, Quang Ninh',
                'image'                 => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
                'price_per_night'       => 180.00,
                'total_rooms'           => 20,
                'max_guests_per_room'   => 2,
                'rating'                => 4.8,
                'description'           => 'Luxury floating hotel on Ha Long Bay with daily kayaking and cave exploration.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 890,
                'distance_from_centre'  => 4.2,
                'latitude'              => 20.9101,
                'longitude'             => 107.1839,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'Waterfront', 'Breakfast Included', 'Towels', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Ha Long Sunset Hostel',
                'city'                  => 'Ha Long',
                'address'               => '55 Vuon Dao, Bai Chay, Ha Long',
                'image'                 => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
                'price_per_night'       => 18.00,
                'total_rooms'           => 20,
                'max_guests_per_room'   => 4,
                'rating'                => 4.2,
                'description'           => 'Budget hostel with bay views, great for solo travelers.',
                'type'                  => 'Hostel',
                'star_rating'           => 2,
                'review_count'          => 240,
                'distance_from_centre'  => 2.0,
                'latitude'              => 20.9580,
                'longitude'             => 107.0730,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Towels']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Vinpearl Resort Ha Long',
                'city'                  => 'Ha Long',
                'address'               => 'Ha Long Bay, Quang Ninh',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 240.00,
                'total_rooms'           => 450,
                'max_guests_per_room'   => 4,
                'rating'                => 4.6,
                'description'           => 'Mega-resort on private island with water park and golf.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 3800,
                'distance_from_centre'  => 6.0,
                'latitude'              => 20.8900,
                'longitude'             => 107.1200,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Waterfront', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],

            // ==================== ĐÀ LẠT ====================
            [
                'name'                  => 'Dalat Highland Retreat',
                'city'                  => 'Da Lat',
                'address'               => '8 Phan Dinh Phung, Da Lat City, Lam Dong',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 55.00,
                'total_rooms'           => 35,
                'max_guests_per_room'   => 3,
                'rating'                => 4.5,
                'description'           => 'French colonial-style hotel surrounded by pine forests and flower gardens.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 450,
                'distance_from_centre'  => 1.5,
                'latitude'              => 11.9404,
                'longitude'             => 108.4583,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Free Parking', 'TV', 'Smoke Alarm']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Debit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Ana Mandara Villas Dalat',
                'city'                  => 'Da Lat',
                'address'               => 'Le Lai Street, Da Lat City',
                'image'                 => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
                'price_per_night'       => 195.00,
                'total_rooms'           => 17,
                'max_guests_per_room'   => 4,
                'rating'                => 4.8,
                'description'           => 'Restored French colonial villas hidden in pine forest gardens.',
                'type'                  => 'Villa',
                'star_rating'           => 5,
                'review_count'          => 720,
                'distance_from_centre'  => 1.0,
                'latitude'              => 11.9450,
                'longitude'             => 108.4420,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Spa access', 'Restaurant', 'Bar', 'Radiant Heating', 'Breakfast Included', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Da Lat Flower Hostel',
                'city'                  => 'Da Lat',
                'address'               => '67 Truong Cong Dinh, Da Lat',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 12.00,
                'total_rooms'           => 15,
                'max_guests_per_room'   => 6,
                'rating'                => 4.4,
                'description'           => 'Cozy hostel in flower city with motorbike rental.',
                'type'                  => 'Hostel',
                'star_rating'           => 2,
                'review_count'          => 310,
                'distance_from_centre'  => 0.5,
                'latitude'              => 11.9380,
                'longitude'             => 108.4380,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Radiant Heating', 'Towels', 'Iron']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],

            // ==================== MŨI NÉ ====================
            [
                'name'                  => 'Mui Ne Beach Club Resort',
                'city'                  => 'Mui Ne',
                'address'               => '24 Nguyen Dinh Chieu, Mui Ne, Binh Thuan',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 110.00,
                'total_rooms'           => 45,
                'max_guests_per_room'   => 3,
                'rating'                => 4.5,
                'description'           => 'Beachfront resort famous for kitesurfing and sand dunes.',
                'type'                  => 'Resort',
                'star_rating'           => 4,
                'review_count'          => 780,
                'distance_from_centre'  => 2.0,
                'latitude'              => 10.9333,
                'longitude'             => 108.2833,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Restaurant', 'Bar', 'Private Beach Area', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Debit Card']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Mui Ne Sailing Club',
                'city'                  => 'Mui Ne',
                'address'               => '24 Nguyen Dinh Chieu, Ham Tien, Mui Ne',
                'image'                 => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600&q=80',
                'price_per_night'       => 85.00,
                'total_rooms'           => 30,
                'max_guests_per_room'   => 2,
                'rating'                => 4.4,
                'description'           => 'Iconic beachside resort with watersports and legendary parties.',
                'type'                  => 'Resort',
                'star_rating'           => 4,
                'review_count'          => 1200,
                'distance_from_centre'  => 1.5,
                'latitude'              => 10.9410,
                'longitude'             => 108.2900,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Restaurant', 'Bar', 'Waterfront']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],

            // ==================== CẦN THƠ ====================
            [
                'name'                  => 'Can Tho Riverside Hotel',
                'city'                  => 'Can Tho',
                'address'               => '2 Hai Ba Trung, Ninh Kieu, Can Tho',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 50.00,
                'total_rooms'           => 40,
                'max_guests_per_room'   => 2,
                'rating'                => 4.3,
                'description'           => 'Riverside hotel with floating market tours and Mekong cruises.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 420,
                'distance_from_centre'  => 0.5,
                'latitude'              => 10.0452,
                'longitude'             => 105.7469,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'TV', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Azerai Can Tho',
                'city'                  => 'Can Tho',
                'address'               => 'Cai Khe, Ninh Kieu District, Can Tho',
                'image'                 => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80',
                'price_per_night'       => 175.00,
                'total_rooms'           => 60,
                'max_guests_per_room'   => 3,
                'rating'                => 4.8,
                'description'           => 'Luxury island resort on the Mekong River with tranquil gardens.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 640,
                'distance_from_centre'  => 3.0,
                'latitude'              => 10.0600,
                'longitude'             => 105.7600,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Restaurant', 'Bar', 'Waterfront', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== PHÚ YÊN ====================
            [
                'name'                  => 'Phu Yen Sunrise Hotel',
                'city'                  => 'Phu Yen',
                'address'               => '1 Hung Vuong, Tuy Hoa, Phu Yen',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 45.00,
                'total_rooms'           => 35,
                'max_guests_per_room'   => 2,
                'rating'                => 4.2,
                'description'           => 'Modern hotel in Tuy Hoa city with ocean views.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 280,
                'distance_from_centre'  => 1.0,
                'latitude'              => 13.0950,
                'longitude'             => 109.3120,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'TV', 'Free Parking']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],

            // ==================== QUY NHƠN ====================
            [
                'name'                  => 'FLC Quy Nhon Beach & Golf Resort',
                'city'                  => 'Quy Nhon',
                'address'               => 'Nhon Ly Commune, Quy Nhon, Binh Dinh',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 130.00,
                'total_rooms'           => 500,
                'max_guests_per_room'   => 4,
                'rating'                => 4.5,
                'description'           => 'Sprawling beachfront resort with golf course on Ky Co beach.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 1600,
                'distance_from_centre'  => 12.0,
                'latitude'              => 13.8500,
                'longitude'             => 109.2000,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Quy Nhon Backpacker',
                'city'                  => 'Quy Nhon',
                'address'               => '18 An Duong Vuong, Quy Nhon',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 14.00,
                'total_rooms'           => 12,
                'max_guests_per_room'   => 6,
                'rating'                => 4.3,
                'description'           => 'Social hostel near Quy Nhon beach for budget travelers.',
                'type'                  => 'Hostel',
                'star_rating'           => 1,
                'review_count'          => 195,
                'distance_from_centre'  => 0.8,
                'latitude'              => 13.7757,
                'longitude'             => 109.2245,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Towels']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],

            // ==================== VŨNG TÀU ====================
            [
                'name'                  => 'Vung Tau Intourco Resort',
                'city'                  => 'Vung Tau',
                'address'               => '22 Tran Phu Street, Vung Tau',
                'image'                 => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600&q=80',
                'price_per_night'       => 90.00,
                'total_rooms'           => 80,
                'max_guests_per_room'   => 3,
                'rating'                => 4.3,
                'description'           => 'Classic beachfront resort popular with Saigon weekenders.',
                'type'                  => 'Resort',
                'star_rating'           => 4,
                'review_count'          => 950,
                'distance_from_centre'  => 1.5,
                'latitude'              => 10.3460,
                'longitude'             => 107.0843,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Restaurant', 'Bar', 'Private Beach Area', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'The Grand Ho Tram Strip',
                'city'                  => 'Vung Tau',
                'address'               => 'Ho Tram Beach, Xuyen Moc, Ba Ria-Vung Tau',
                'image'                 => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
                'price_per_night'       => 260.00,
                'total_rooms'           => 541,
                'max_guests_per_room'   => 4,
                'rating'                => 4.6,
                'description'           => 'Vegas-style luxury resort with casino on Ho Tram beach.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 2100,
                'distance_from_centre'  => 15.0,
                'latitude'              => 10.5000,
                'longitude'             => 107.5000,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Hot Tub', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== NINH BÌNH ====================
            [
                'name'                  => 'Emeralda Resort Ninh Binh',
                'city'                  => 'Ninh Binh',
                'address'               => 'Van Long Nature Reserve, Ninh Binh',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 155.00,
                'total_rooms'           => 96,
                'max_guests_per_room'   => 3,
                'rating'                => 4.8,
                'description'           => 'Eco-resort in traditional Vietnamese village style near Trang An.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 1050,
                'distance_from_centre'  => 8.0,
                'latitude'              => 20.2800,
                'longitude'             => 105.9500,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Restaurant', 'Bar', 'Waterfront', 'Breakfast Included', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Ninh Binh Hidden Cave Homestay',
                'city'                  => 'Ninh Binh',
                'address'               => 'Tam Coc, Ninh Binh',
                'image'                 => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
                'price_per_night'       => 28.00,
                'total_rooms'           => 12,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Peaceful homestay near Tam Coc with rice field cycling tours.',
                'type'                  => 'Guest House',
                'star_rating'           => 2,
                'review_count'          => 310,
                'distance_from_centre'  => 5.0,
                'latitude'              => 20.2300,
                'longitude'             => 105.9100,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Breakfast Included', 'Free Parking', 'Towels']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],

            // ==================== CÔN ĐẢO ====================
            [
                'name'                  => 'Six Senses Con Dao',
                'city'                  => 'Con Dao',
                'address'               => 'Con Dao Island, Ba Ria-Vung Tau',
                'image'                 => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80',
                'price_per_night'       => 850.00,
                'total_rooms'           => 50,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Voted world\'s best resort. Private villas on pristine Con Dao island.',
                'type'                  => 'Villa',
                'star_rating'           => 5,
                'review_count'          => 1400,
                'distance_from_centre'  => 3.0,
                'latitude'              => 8.6800,
                'longitude'             => 106.6100,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Restaurant', 'Bar', 'Private Beach Area', 'Waterfront', 'Hot Tub', 'BBQ Grill']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
                'status'                => 'approved',
            ],

            // ==================== LÝ SƠN ====================
            [
                'name'                  => 'Ly Son Pearl Island Hotel',
                'city'                  => 'Ly Son',
                'address'               => 'Ly Son Island, Quang Ngai',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 65.00,
                'total_rooms'           => 25,
                'max_guests_per_room'   => 3,
                'rating'                => 4.4,
                'description'           => 'Boutique hotel on the volcanic island of Ly Son.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 190,
                'distance_from_centre'  => 1.0,
                'latitude'              => 15.3730,
                'longitude'             => 109.1250,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Free Parking']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
                'status'                => 'approved',
            ],

            // ==================== HÀ GIANG ====================
            [
                'name'                  => 'Ha Giang Rock Homestay',
                'city'                  => 'Ha Giang',
                'address'               => 'Dong Van Stone Plateau, Ha Giang',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 20.00,
                'total_rooms'           => 8,
                'max_guests_per_room'   => 4,
                'rating'                => 4.8,
                'description'           => 'Authentic homestay on the UNESCO Dong Van Karst Plateau.',
                'type'                  => 'Guest House',
                'star_rating'           => 1,
                'review_count'          => 145,
                'distance_from_centre'  => 5.0,
                'latitude'              => 23.2700,
                'longitude'             => 105.3600,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Breakfast Included', 'Towels']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],
            [
                'name'                  => 'Ha Giang Loop Hostel',
                'city'                  => 'Ha Giang',
                'address'               => '10 Nguyen Trai, Ha Giang City',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 10.00,
                'total_rooms'           => 15,
                'max_guests_per_room'   => 8,
                'rating'                => 4.5,
                'description'           => 'The go-to base for motorbike loop riders in Ha Giang.',
                'type'                  => 'Hostel',
                'star_rating'           => 1,
                'review_count'          => 380,
                'distance_from_centre'  => 0.5,
                'latitude'              => 22.8230,
                'longitude'             => 104.9836,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Towels', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Cash']),
                'status'                => 'approved',
            ],

            // ==================== PHAN THIẾT ====================
            [
                'name'                  => 'Anantara Mui Ne Resort',
                'city'                  => 'Phan Thiet',
                'address'               => 'Phu Hai, Phan Thiet, Binh Thuan',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 190.00,
                'total_rooms'           => 89,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Luxury resort on Mui Ne beach with colonial-era architecture.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 1350,
                'distance_from_centre'  => 4.0,
                'latitude'              => 10.9260,
                'longitude'             => 108.2640,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Spa access', 'Gym', 'Restaurant', 'Bar', 'Private Beach Area', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'PayPal']),
                'status'                => 'approved',
            ],
        ];

        foreach ($hotels as $hotel) {
            DB::table('hotels')->insert(array_merge($hotel, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}
