<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name'                  => 'The Grand Hanoi Hotel',
                'city'                  => 'Hanoi',
                'address'               => '49 Ba Trieu Street, Hoan Kiem, Hanoi',
                'image'                 => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
                'price_per_night'       => 120.00,
                'total_rooms'           => 80,
                'max_guests_per_room'   => 3,
                'rating'                => 4.7,
                'description'           => 'Luxury hotel in the heart of Hanoi Old Quarter with stunning views of Hoan Kiem Lake.',
                'type'                  => 'Hotel',
                'star_rating'           => 5,
                'review_count'          => 1250,
                'distance_from_centre'  => 0.5,
                'latitude'              => 21.0285,
                'longitude'             => 105.8542,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Pool', 'Gym', 'Restaurant', 'Bar', 'Free Parking', 'Spa access']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash']),
            ],
            [
                'name'                  => 'Saigon Riverside Hotel',
                'city'                  => 'Ho Chi Minh City',
                'address'               => '18 Ton Duc Thang, District 1, Ho Chi Minh City',
                'image'                 => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
                'price_per_night'       => 95.00,
                'total_rooms'           => 120,
                'max_guests_per_room'   => 2,
                'rating'                => 4.5,
                'description'           => 'Modern hotel with panoramic views of the Saigon River, steps from Ben Thanh Market.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 980,
                'distance_from_centre'  => 1.2,
                'latitude'              => 10.7769,
                'longitude'             => 106.7009,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'TV', 'Balcony']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Bank Transfer']),
            ],
            [
                'name'                  => 'Da Nang Beach Resort',
                'city'                  => 'Da Nang',
                'address'               => '30 Vo Nguyen Giap, My An, Da Nang',
                'image'                 => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
                'price_per_night'       => 150.00,
                'total_rooms'           => 60,
                'max_guests_per_room'   => 4,
                'rating'                => 4.8,
                'description'           => 'Beachfront resort on My Khe Beach with private pool and direct sea access.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 2100,
                'distance_from_centre'  => 3.5,
                'latitude'              => 16.0544,
                'longitude'             => 108.2022,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Gym', 'Spa access', 'Restaurant', 'Private Beach Area', 'Free Parking', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash', 'PayPal']),
            ],
            [
                'name'                  => 'Hoi An Ancient Town Boutique',
                'city'                  => 'Hoi An',
                'address'               => '5 Le Loi Street, Hoi An Ancient Town',
                'image'                 => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
                'price_per_night'       => 85.00,
                'total_rooms'           => 30,
                'max_guests_per_room'   => 2,
                'rating'                => 4.9,
                'description'           => 'Charming boutique hotel inside the UNESCO-listed Hoi An Ancient Town.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 760,
                'distance_from_centre'  => 0.3,
                'latitude'              => 15.8800,
                'longitude'             => 108.3380,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Balcony', 'TV', 'Towels', 'Hangers']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash']),
            ],
            [
                'name'                  => 'Phu Quoc Paradise Villa',
                'city'                  => 'Phu Quoc',
                'address'               => 'Long Beach Road, Duong To, Phu Quoc',
                'image'                 => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
                'price_per_night'       => 200.00,
                'total_rooms'           => 40,
                'max_guests_per_room'   => 4,
                'rating'                => 4.9,
                'description'           => 'Overwater villas with private plunge pools overlooking the Gulf of Thailand.',
                'type'                  => 'Villa',
                'star_rating'           => 5,
                'review_count'          => 430,
                'distance_from_centre'  => 5.0,
                'latitude'              => 10.2899,
                'longitude'             => 103.9840,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Hot Tub', 'Kitchen', 'Waterfront', 'Private Beach Area', 'BBQ Grill', 'Free Parking']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer', 'PayPal']),
            ],
            [
                'name'                  => 'Nha Trang Ocean View',
                'city'                  => 'Nha Trang',
                'address'               => '78 Tran Phu Boulevard, Nha Trang',
                'image'                 => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600&q=80',
                'price_per_night'       => 75.00,
                'total_rooms'           => 100,
                'max_guests_per_room'   => 3,
                'rating'                => 4.3,
                'description'           => 'Seafront hotel on the famous Nha Trang beach promenade with rooftop bar.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 1540,
                'distance_from_centre'  => 1.8,
                'latitude'  => 12.2388,
                'longitude' => 109.1967,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Bar', 'Restaurant', 'TV', 'Smoke Alarm', 'Carbon monoxide Alarm']),
                'payment_methods'       => json_encode(['Credit Card', 'Debit Card', 'Cash']),
            ],
            [
                'name'                  => 'Sapa Mountain Lodge',
                'city'                  => 'Sapa',
                'address'               => '12 Muong Hoa Road, Sapa Town, Lao Cai',
                'image'                 => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'price_per_night'       => 60.00,
                'total_rooms'           => 25,
                'max_guests_per_room'   => 2,
                'rating'                => 4.6,
                'description'           => 'Cozy mountain lodge with valley views, fireplace, and daily trekking tours.',
                'type'                  => 'Guest House',
                'star_rating'           => 3,
                'review_count'          => 320,
                'distance_from_centre'  => 2.1,
                'latitude'  => 22.3364,
                'longitude' => 103.8438,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Radiant Heating', 'Iron', 'Towels', 'Smoke Alarm']),
                'payment_methods'       => json_encode(['Cash', 'Credit Card']),
            ],
            [
                'name'                  => 'Hue Imperial Palace Hotel',
                'city'                  => 'Hue',
                'address'               => '23 Le Loi Street, Hue City',
                'image'                 => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
                'price_per_night'       => 70.00,
                'total_rooms'           => 50,
                'max_guests_per_room'   => 2,
                'rating'                => 4.4,
                'description'           => 'Heritage hotel near the Imperial Citadel with traditional Vietnamese architecture.',
                'type'                  => 'Hotel',
                'star_rating'           => 4,
                'review_count'          => 610,
                'distance_from_centre'  => 1.0,
                'latitude'  => 16.4637,
                'longitude' => 107.5909,
                'free_cancellation'     => true,
                'instant_booking'       => false,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => true,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'TV', 'Hair dryer', 'Safe', 'Hangers', 'Breakfast Included']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Bank Transfer']),
            ],
            [
                'name'                  => 'Ha Long Bay Cruise Hotel',
                'city'                  => 'Ha Long',
                'address'               => 'Hon Gai Harbour, Ha Long City, Quang Ninh',
                'image'                 => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
                'price_per_night'       => 180.00,
                'total_rooms'           => 20,
                'max_guests_per_room'   => 2,
                'rating'                => 4.8,
                'description'           => 'Luxury floating hotel on Ha Long Bay with daily kayaking and cave exploration.',
                'type'                  => 'Resort',
                'star_rating'           => 5,
                'review_count'          => 890,
                'distance_from_centre'  => 4.2,
                'latitude'  => 20.9101,
                'longitude' => 107.1839,
                'free_cancellation'     => false,
                'instant_booking'       => false,
                'pay_at_property'       => false,
                'pay_later'             => false,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'Waterfront', 'Breakfast Included', 'Towels', 'Safe']),
                'payment_methods'       => json_encode(['Credit Card', 'Bank Transfer']),
            ],
            [
                'name'                  => 'Dalat Highland Retreat',
                'city'                  => 'Da Lat',
                'address'               => '8 Phan Dinh Phung, Da Lat City, Lam Dong',
                'image'                 => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
                'price_per_night'       => 55.00,
                'total_rooms'           => 35,
                'max_guests_per_room'   => 3,
                'rating'                => 4.5,
                'description'           => 'French colonial-style hotel surrounded by pine forests and flower gardens.',
                'type'                  => 'Hotel',
                'star_rating'           => 3,
                'review_count'          => 450,
                'distance_from_centre'  => 1.5,
                'latitude'  => 11.9404,
                'longitude' => 108.4583,
                'free_cancellation'     => true,
                'instant_booking'       => true,
                'pay_at_property'       => true,
                'pay_later'             => true,
                'wheelchair_accessible' => false,
                'amenities'             => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Free Parking', 'TV', 'Iron', 'Hair dryer', 'Smoke Alarm', 'Carbon monoxide Alarm']),
                'payment_methods'       => json_encode(['Credit Card', 'Cash', 'Debit Card']),
            ],
        ];

        foreach ($hotels as $hotel) {
            DB::table('hotels')->insert(array_merge($hotel, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}
