<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            // ── Hanoi ───────────────────────────────────────────
            ['name' => 'The Grand Hanoi Hotel', 'city' => 'Hanoi', 'address' => '49 Ba Trieu Street, Hoan Kiem, Hanoi', 'image' => 'images/hotels/grand-hanoi.jpg', 'price_per_night' => 120.00, 'total_rooms' => 80, 'max_guests_per_room' => 3, 'rating' => 4.7, 'description' => 'Luxury hotel in the heart of Hanoi Old Quarter with stunning views of Hoan Kiem Lake.', 'type' => 'Hotel', 'star_rating' => 5, 'review_count' => 1250, 'distance_from_centre' => 0.5, 'latitude' => 21.0285, 'longitude' => 105.8542, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Pool', 'Gym', 'Restaurant', 'Bar', 'Free Parking', 'Spa access']), 'payment_methods' => json_encode(['Credit Card', 'Debit Card', 'Cash'])],
            ['name' => 'Hanoi Old Quarter Hostel', 'city' => 'Hanoi', 'address' => '25 Hang Bac Street, Hoan Kiem, Hanoi', 'image' => 'images/hotels/grand-hanoi.jpg', 'price_per_night' => 25.00, 'total_rooms' => 20, 'max_guests_per_room' => 4, 'rating' => 4.2, 'description' => 'Budget-friendly hostel in the heart of the Old Quarter, perfect for backpackers.', 'type' => 'Hostel', 'star_rating' => 2, 'review_count' => 540, 'distance_from_centre' => 0.3, 'latitude' => 21.0340, 'longitude' => 105.8520, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'TV', 'Towels']), 'payment_methods' => json_encode(['Cash', 'Credit Card'])],

            // ── Ho Chi Minh City ────────────────────────────────
            ['name' => 'Saigon Riverside Hotel', 'city' => 'Ho Chi Minh City', 'address' => '18 Ton Duc Thang, District 1, Ho Chi Minh City', 'image' => 'images/hotels/saigon-riverside.jpg', 'price_per_night' => 95.00, 'total_rooms' => 120, 'max_guests_per_room' => 2, 'rating' => 4.5, 'description' => 'Modern hotel with panoramic views of the Saigon River, steps from Ben Thanh Market.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 980, 'distance_from_centre' => 1.2, 'latitude' => 10.7769, 'longitude' => 106.7009, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'TV', 'Balcony']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Bank Transfer'])],
            ['name' => 'Saigon Central Apartment', 'city' => 'Ho Chi Minh City', 'address' => '52 Nguyen Hue Boulevard, District 1, Ho Chi Minh City', 'image' => 'images/hotels/saigon-riverside.jpg', 'price_per_night' => 65.00, 'total_rooms' => 45, 'max_guests_per_room' => 4, 'rating' => 4.4, 'description' => 'Modern serviced apartments on the iconic Nguyen Hue Walking Street with city views.', 'type' => 'Apartment', 'star_rating' => 3, 'review_count' => 420, 'distance_from_centre' => 0.5, 'latitude' => 10.7740, 'longitude' => 106.7030, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Kitchen', 'TV', 'Washing machine', 'Free Parking']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'PayPal'])],

            // ── Da Nang ─────────────────────────────────────────
            ['name' => 'Da Nang Beach Resort', 'city' => 'Da Nang', 'address' => '30 Vo Nguyen Giap, My An, Da Nang', 'image' => 'images/hotels/danang-beach.jpg', 'price_per_night' => 150.00, 'total_rooms' => 60, 'max_guests_per_room' => 4, 'rating' => 4.8, 'description' => 'Beachfront resort on My Khe Beach with private pool and direct sea access.', 'type' => 'Resort', 'star_rating' => 5, 'review_count' => 2100, 'distance_from_centre' => 3.5, 'latitude' => 16.0544, 'longitude' => 108.2022, 'free_cancellation' => true, 'instant_booking' => false, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Gym', 'Spa access', 'Restaurant', 'Private Beach Area', 'Free Parking', 'Breakfast Included']), 'payment_methods' => json_encode(['Credit Card', 'Debit Card', 'Cash', 'PayPal'])],
            ['name' => 'Da Nang City Center Hotel', 'city' => 'Da Nang', 'address' => '120 Bach Dang Street, Hai Chau, Da Nang', 'image' => 'images/hotels/danang-beach.jpg', 'price_per_night' => 55.00, 'total_rooms' => 70, 'max_guests_per_room' => 2, 'rating' => 4.1, 'description' => 'Comfortable city hotel near Han River Bridge with easy access to beaches and attractions.', 'type' => 'Hotel', 'star_rating' => 3, 'review_count' => 380, 'distance_from_centre' => 1.0, 'latitude' => 16.0678, 'longitude' => 108.2200, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'TV', 'Restaurant', 'Breakfast Included']), 'payment_methods' => json_encode(['Credit Card', 'Cash'])],

            // ── Hoi An ──────────────────────────────────────────
            ['name' => 'Hoi An Ancient Town Boutique', 'city' => 'Hoi An', 'address' => '5 Le Loi Street, Hoi An Ancient Town', 'image' => 'images/hotels/hoian-boutique.jpg', 'price_per_night' => 85.00, 'total_rooms' => 30, 'max_guests_per_room' => 2, 'rating' => 4.9, 'description' => 'Charming boutique hotel inside the UNESCO-listed Hoi An Ancient Town.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 760, 'distance_from_centre' => 0.3, 'latitude' => 15.8800, 'longitude' => 108.3380, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Balcony', 'TV', 'Towels', 'Hangers']), 'payment_methods' => json_encode(['Credit Card', 'Cash'])],
            ['name' => 'Hoi An Riverside Villa', 'city' => 'Hoi An', 'address' => '18 Cua Dai Road, Hoi An', 'image' => 'images/hotels/hoian-boutique.jpg', 'price_per_night' => 110.00, 'total_rooms' => 15, 'max_guests_per_room' => 4, 'rating' => 4.7, 'description' => 'Peaceful riverside villa with traditional garden, pool and bicycle rental.', 'type' => 'Villa', 'star_rating' => 4, 'review_count' => 290, 'distance_from_centre' => 1.5, 'latitude' => 15.8750, 'longitude' => 108.3500, 'free_cancellation' => true, 'instant_booking' => false, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Breakfast Included', 'Balcony', 'Waterfront', 'BBQ Grill']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Bank Transfer'])],

            // ── Phu Quoc ────────────────────────────────────────
            ['name' => 'Phu Quoc Paradise Villa', 'city' => 'Phu Quoc', 'address' => 'Long Beach Road, Duong To, Phu Quoc', 'image' => 'images/hotels/phuquoc-villa.jpg', 'price_per_night' => 200.00, 'total_rooms' => 40, 'max_guests_per_room' => 4, 'rating' => 4.9, 'description' => 'Overwater villas with private plunge pools overlooking the Gulf of Thailand.', 'type' => 'Villa', 'star_rating' => 5, 'review_count' => 430, 'distance_from_centre' => 5.0, 'latitude' => 10.2899, 'longitude' => 103.9840, 'free_cancellation' => false, 'instant_booking' => false, 'pay_at_property' => false, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Hot Tub', 'Kitchen', 'Waterfront', 'Private Beach Area', 'BBQ Grill', 'Free Parking']), 'payment_methods' => json_encode(['Credit Card', 'Bank Transfer', 'PayPal'])],
            ['name' => 'Phu Quoc Sunset Beach Resort', 'city' => 'Phu Quoc', 'address' => 'Tran Hung Dao Street, Duong To, Phu Quoc', 'image' => 'images/hotels/phuquoc-villa.jpg', 'price_per_night' => 135.00, 'total_rooms' => 55, 'max_guests_per_room' => 3, 'rating' => 4.6, 'description' => 'Sunset-facing resort on Phu Quoc western coast with infinity pool and seafood restaurant.', 'type' => 'Resort', 'star_rating' => 4, 'review_count' => 680, 'distance_from_centre' => 3.2, 'latitude' => 10.3100, 'longitude' => 103.9650, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Restaurant', 'Bar', 'Spa access', 'Private Beach Area', 'Free Parking']), 'payment_methods' => json_encode(['Credit Card', 'Debit Card', 'Cash'])],

            // ── Nha Trang ───────────────────────────────────────
            ['name' => 'Nha Trang Ocean View', 'city' => 'Nha Trang', 'address' => '78 Tran Phu Boulevard, Nha Trang', 'image' => 'images/hotels/nhatrang-ocean.jpg', 'price_per_night' => 75.00, 'total_rooms' => 100, 'max_guests_per_room' => 3, 'rating' => 4.3, 'description' => 'Seafront hotel on the famous Nha Trang beach promenade with rooftop bar.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 1540, 'distance_from_centre' => 1.8, 'latitude' => 12.2388, 'longitude' => 109.1967, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Bar', 'Restaurant', 'TV', 'Smoke Alarm', 'Carbon monoxide Alarm']), 'payment_methods' => json_encode(['Credit Card', 'Debit Card', 'Cash'])],
            ['name' => 'Nha Trang Pearl Hotel', 'city' => 'Nha Trang', 'address' => '10 Biet Thu Street, Nha Trang', 'image' => 'images/hotels/nhatrang-ocean.jpg', 'price_per_night' => 90.00, 'total_rooms' => 80, 'max_guests_per_room' => 2, 'rating' => 4.5, 'description' => 'Elegant hotel in the heart of Nha Trang with rooftop pool and panoramic sea views.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 870, 'distance_from_centre' => 0.8, 'latitude' => 12.2450, 'longitude' => 109.1940, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Pool', 'Air Conditioning', 'Gym', 'Restaurant', 'Bar', 'Breakfast Included', 'Spa access']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Debit Card'])],

            // ── Sapa ────────────────────────────────────────────
            ['name' => 'Sapa Mountain Lodge', 'city' => 'Sapa', 'address' => '12 Muong Hoa Road, Sapa Town, Lao Cai', 'image' => 'images/hotels/sapa-lodge.jpg', 'price_per_night' => 60.00, 'total_rooms' => 25, 'max_guests_per_room' => 2, 'rating' => 4.6, 'description' => 'Cozy mountain lodge with valley views, fireplace, and daily trekking tours.', 'type' => 'Guest House', 'star_rating' => 3, 'review_count' => 320, 'distance_from_centre' => 2.1, 'latitude' => 22.3364, 'longitude' => 103.8438, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Radiant Heating', 'Iron', 'Towels', 'Smoke Alarm']), 'payment_methods' => json_encode(['Cash', 'Credit Card'])],
            ['name' => 'Sapa Eco Valley Resort', 'city' => 'Sapa', 'address' => 'Ban Cat Cat Village, Sapa, Lao Cai', 'image' => 'images/hotels/sapa-lodge.jpg', 'price_per_night' => 80.00, 'total_rooms' => 18, 'max_guests_per_room' => 2, 'rating' => 4.8, 'description' => 'Eco-resort nestled in rice terraces with stunning valley views and ethnic cultural experiences.', 'type' => 'Resort', 'star_rating' => 4, 'review_count' => 410, 'distance_from_centre' => 3.0, 'latitude' => 22.3200, 'longitude' => 103.8300, 'free_cancellation' => true, 'instant_booking' => false, 'pay_at_property' => false, 'pay_later' => true, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Breakfast Included', 'Radiant Heating', 'Balcony', 'Free Parking', 'BBQ Grill']), 'payment_methods' => json_encode(['Cash', 'Credit Card', 'Bank Transfer'])],

            // ── Hue ─────────────────────────────────────────────
            ['name' => 'Hue Imperial Palace Hotel', 'city' => 'Hue', 'address' => '23 Le Loi Street, Hue City', 'image' => 'images/hotels/hue-imperial.jpg', 'price_per_night' => 70.00, 'total_rooms' => 50, 'max_guests_per_room' => 2, 'rating' => 4.4, 'description' => 'Heritage hotel near the Imperial Citadel with traditional Vietnamese architecture.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 610, 'distance_from_centre' => 1.0, 'latitude' => 16.4637, 'longitude' => 107.5909, 'free_cancellation' => true, 'instant_booking' => false, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'TV', 'Hair dryer', 'Safe', 'Hangers', 'Breakfast Included']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Bank Transfer'])],
            ['name' => 'Hue Serene Boutique', 'city' => 'Hue', 'address' => '8 Nguyen Thai Hoc, Hue City', 'image' => 'images/hotels/hue-imperial.jpg', 'price_per_night' => 45.00, 'total_rooms' => 22, 'max_guests_per_room' => 2, 'rating' => 4.3, 'description' => 'Quiet boutique hotel near the Perfume River with rooftop terrace and local breakfast.', 'type' => 'Hotel', 'star_rating' => 3, 'review_count' => 215, 'distance_from_centre' => 1.8, 'latitude' => 16.4600, 'longitude' => 107.5950, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Balcony', 'TV', 'Iron']), 'payment_methods' => json_encode(['Cash', 'Credit Card'])],

            // ── Ha Long ─────────────────────────────────────────
            ['name' => 'Ha Long Bay Cruise Hotel', 'city' => 'Ha Long', 'address' => 'Hon Gai Harbour, Ha Long City, Quang Ninh', 'image' => 'images/hotels/halong-cruise.jpg', 'price_per_night' => 180.00, 'total_rooms' => 20, 'max_guests_per_room' => 2, 'rating' => 4.8, 'description' => 'Luxury floating hotel on Ha Long Bay with daily kayaking and cave exploration.', 'type' => 'Resort', 'star_rating' => 5, 'review_count' => 890, 'distance_from_centre' => 4.2, 'latitude' => 20.9101, 'longitude' => 107.1839, 'free_cancellation' => false, 'instant_booking' => false, 'pay_at_property' => false, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Restaurant', 'Bar', 'Waterfront', 'Breakfast Included', 'Towels', 'Safe']), 'payment_methods' => json_encode(['Credit Card', 'Bank Transfer'])],
            ['name' => 'Ha Long Bay View Hotel', 'city' => 'Ha Long', 'address' => 'Bai Chay Tourist Area, Ha Long City', 'image' => 'images/hotels/halong-cruise.jpg', 'price_per_night' => 85.00, 'total_rooms' => 65, 'max_guests_per_room' => 3, 'rating' => 4.4, 'description' => 'Modern hotel with bay views in Bai Chay area, close to ferry terminals and night market.', 'type' => 'Hotel', 'star_rating' => 4, 'review_count' => 560, 'distance_from_centre' => 2.5, 'latitude' => 20.9600, 'longitude' => 107.0500, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => true, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Pool', 'Restaurant', 'Bar', 'TV', 'Free Parking']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Debit Card'])],

            // ── Da Lat ──────────────────────────────────────────
            ['name' => 'Dalat Highland Retreat', 'city' => 'Da Lat', 'address' => '8 Phan Dinh Phung, Da Lat City, Lam Dong', 'image' => 'images/hotels/dalat-highland.jpg', 'price_per_night' => 55.00, 'total_rooms' => 35, 'max_guests_per_room' => 3, 'rating' => 4.5, 'description' => 'French colonial-style hotel surrounded by pine forests and flower gardens.', 'type' => 'Hotel', 'star_rating' => 3, 'review_count' => 450, 'distance_from_centre' => 1.5, 'latitude' => 11.9404, 'longitude' => 108.4583, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => true, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Free Parking', 'TV', 'Iron', 'Hair dryer', 'Smoke Alarm', 'Carbon monoxide Alarm']), 'payment_methods' => json_encode(['Credit Card', 'Cash', 'Debit Card'])],
            ['name' => 'Dalat Flower Garden Hotel', 'city' => 'Da Lat', 'address' => '64 Tran Phu Street, Da Lat City', 'image' => 'images/hotels/dalat-highland.jpg', 'price_per_night' => 40.00, 'total_rooms' => 28, 'max_guests_per_room' => 2, 'rating' => 4.2, 'description' => 'Charming hotel surrounded by Dalat flower gardens with mountain views and fireplace rooms.', 'type' => 'Hotel', 'star_rating' => 3, 'review_count' => 310, 'distance_from_centre' => 0.8, 'latitude' => 11.9450, 'longitude' => 108.4420, 'free_cancellation' => true, 'instant_booking' => true, 'pay_at_property' => true, 'pay_later' => false, 'wheelchair_accessible' => false, 'amenities' => json_encode(['Wi-Fi', 'Air Conditioning', 'Breakfast Included', 'Radiant Heating', 'TV', 'Hair dryer']), 'payment_methods' => json_encode(['Cash', 'Credit Card'])],
        ];

        foreach ($hotels as $hotel) {
            DB::table('hotels')->insert(array_merge($hotel, [
                'status'     => 'approved',
                'owner_id'   => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}
